Portfolio implementation: Microverse-Portfolio
Graycemuthui/Microverse-Portfolio pull request #10
Opened 2022-05-12 15:52 UTC by Graycemuthui

Created a popup that brings out the content of the cards.
Created functionality for the popup.
Followed proper github flow.

2022-05-12 17:39 UTC, zieeco requested changes
Hi @Graycemuthui 


Great work with the popup window 👏 
You've done well implementing it, however, there are some issues that you still need to work on to go to the next project, but you are almost there!


## To highlight 🎯

- No linter errors.✔️
- Nice design. ✔️
- Descriptive PR. ✔️


## Required Changes ♻️
_Check the comments under the review._


<img src="https://media0.giphy.com/media/8UGVQESpDMMQl7yd3F/giphy.gif"/>


## Optional suggestions
- Add a margin-top of 14px to your `.card-image` in your syle.css line 197 to move the image down a bit

**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-12 17:39 UTC, zieeco commented on css/styles.css
> +  }
- [ ] Hey, your popUp window looks great, however, you have some small issues that need to be addressed: kindly do the following:

- Play around with the `top: -55%` by removing it to make your popUp cancel button visible so that a user can close the popUp window
- Your see live and see source button do not match the figma design, please, kindly fix this below:


**FIGMA**

![match2](https://user-images.githubusercontent.com/59397159/168132556-3fc550d2-fa2c-4c89-91d0-8a2c818f5390.png)

**YOUR DESIGN**

![match](https://user-images.githubusercontent.com/59397159/168132562-2d330f21-a819-44d7-8512-c06637e598cf.png)

2022-05-12 17:39 UTC, zieeco commented on css/styles.css
> +
**[REQUIRED CHANGES]**

- Please, kindly adjust your styling on your mobile version so that a user can see all the contents in your modal. right now, a user is stuck on viewing all the contents of your project, they can only see the image and little of the description.
The languages, see live, and see source button is not showing.
Please, kindly fix this to improve the user experience.

2022-05-12 20:41 UTC, zainsadaqat requested changes
# Required Changes 🔁 
# Hello  @Graycemuthui 😃 

You're doing a great job on your project. We're proud of you. Good job so far! 

There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
  ✅  Correct use of Github Flow
  ✅  No linter errors
  ✅  Descriptive Pull Request

## Required Changes ♻️

As requested by the previous code reviewer, Kindly fix the top of the popup window.  👍🏻 

[Optional]
I'm sorry, previous code reviewers couldn't catch this but it's showing the same popup window for all the projects.

As you may have lost all review attempts but you can still use extra reviews 👍🏻 😄 

_Check the comments under the review._


<img src="https://media0.giphy.com/media/QvMIzHw30MmMAqvOeo/giphy.gif"/>

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding! 👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-13 07:09 UTC, danmainah approved these changes
Hi @Graycemuthui, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 

## Highlights
✔️ No linter errors
✔️ Github flow was correctly used
✔️  Good design
✔️  Good PR and Description

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-13 07:13 UTC, merged